# https://developers.cloudflare.com/api/operations/worker-deployments-create-deployment
#注意key的权限需要写
name: Deployment Vless Sub
on:
  push:
    branches: 
      - master  # Make sure the indentation is correct here
  workflow_dispatch: # This is fine if you don't want to pass any inputs

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Make sure to check out the repository's code
      - name: Deploy to Cloudflare
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          RESPONSE=$(curl --silent --request POST \
          --url "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/workers/scripts/vless2sub/deployments" \
          --header "Authorization: Bearer ${CF_TOKEN}" \
          --header "Content-Type: application/json" \
          --data '{
            "metadata": {
              "body_part": "workers_script",
              "bindings": []
            },
            "deployment": {
              "routes": [
                "http://*myworkers.dev/*"
              ]
            },
            "migrations": []
          }')
          if [ $? -ne 0 ]; then
            echo "Error deploying to Cloudflare"
            echo "$RESPONSE"
            exit 1
          fi     