# https://developers.cloudflare.com/api/operations/worker-deployments-create-deployment
#注意key的权限需要写
name: Deployment Vless Sub
on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cloudflare
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |-
          curl --request POST \
          --url https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/workers/scripts/vless2sub/deployments \
          --header "Authorization: Bearer ${CF_TOKEN}" \
          --header 'Content-Type: application/json' \
          --data '{
            "annotations": {
              "workers/message": "Deploy update ip."
            },
            "strategy": "percentage",
            "versions": [
              {
                "percentage": 100,
                "version_id": "30a2a606-c9b4-4520-b1e2-017204b42efc"
              }
            ]
          }'
          if [ $? -ne 0 ]; then
            echo "Error deploying to Cloudflare"
            exit 1
          fi